// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYkhs_92OP_vnQ2T_YI3YGzyi-qNDqwok',
    appId: '1:301045802696:web:f138532a2befa066b8a7fd',
    messagingSenderId: '301045802696',
    projectId: 'grown-out',
    authDomain: 'grown-out.firebaseapp.com',
    storageBucket: 'grown-out.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW_hNZsKfKrQzCaKZEe3mfNuBI3t7PyD4',
    appId: '1:301045802696:android:3b388b6cd6128e7bb8a7fd',
    messagingSenderId: '301045802696',
    projectId: 'grown-out',
    storageBucket: 'grown-out.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB23Mn7yhzH5J9orzqj3zlIMo4eHj79-Z8',
    appId: '1:301045802696:ios:cd513bc10bd027feb8a7fd',
    messagingSenderId: '301045802696',
    projectId: 'grown-out',
    storageBucket: 'grown-out.appspot.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYkhs_92OP_vnQ2T_YI3YGzyi-qNDqwok',
    appId: '1:301045802696:web:670396a647822a93b8a7fd',
    messagingSenderId: '301045802696',
    projectId: 'grown-out',
    authDomain: 'grown-out.firebaseapp.com',
    storageBucket: 'grown-out.appspot.com',
  );

}